name: KiwiClaims
version: 0.0.1-SNAPSHOT
main: me.MFHKiwi.KiwiClaims.KiwiClaims
description: A claims plugin for CraftBukkit 1060.
author: MFHKiwi
commands:
   kc:
      description: Interact with KiwiClaims
      usage: /kc <argument>
      aliases: [kiwiclaims, kclaims, claims, claim]
permissions:
   kc.use:
      description: Use /kc
      default: true
   kc.admin:
      description: Use admin functions
      default: op